@echo off
setlocal enabledelayedexpansion
echo ========================================
echo   DSQ SYSTEM - ALTERNATIVE 24/7 RUNNER
echo   (No Windows Service Required)
echo ========================================
echo.

REM Read IP from .env file
echo Checking configuration...
if exist "%~dp0frontend\.env" (
    echo ✓ Frontend .env file found
    findstr /i "VITE_API_URL" "%~dp0frontend\.env" 2>nul | findstr /v /i "SECRET_KEY PASSWORD TOKEN"
) else (
    echo Frontend .env will be auto-generated by the app
)

if exist "%~dp0backend\.env" (
    echo ✓ Backend .env file found
    findstr /i "VITE_API_URL" "%~dp0backend\.env" 2>nul | findstr /v /i "SECRET_KEY PASSWORD TOKEN"
    echo   SECRET_KEY=***HIDDEN FOR SECURITY***
) else (
    echo Backend .env will be auto-generated by the app
)

REM Get current machine IP
echo Detecting current IP address...
REM First try to get Ethernet adapter IP
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /A:"Ethernet adapter Ethernet" -A 10 ^| findstr /c:"IPv4 Address"') do (
    set "MACHINE_IP=%%a"
    set "MACHINE_IP=!MACHINE_IP: =!"
    if not "!MACHINE_IP!"=="127.0.0.1" if not "!MACHINE_IP!"=="" (
        goto :ip_found
    )
)
REM Fallback to any non-loopback IPv4 address
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set "TEMP_IP=%%a"
    set "TEMP_IP=!TEMP_IP: =!"
    if not "!TEMP_IP!"=="127.0.0.1" if not "!TEMP_IP!"=="" if not "!TEMP_IP:~0,11!"=="192.168.137" (
        set "MACHINE_IP=!TEMP_IP!"
        goto :ip_found
    )
)
:ip_found
if defined MACHINE_IP (
    echo Current machine IP: %MACHINE_IP%
) else (
    echo Could not detect IP, using localhost
    set "MACHINE_IP=localhost"
)

echo.
echo ========================================
echo Starting DSQ System (24/7 Mode)...
echo ========================================

REM Find best Python
set "PYTHON_CMD=python"

REM Try py launcher first
py --version >nul 2>&1
if %errorlevel% equ 0 (
    py -m pip show uvicorn >nul 2>&1
    if !errorlevel! equ 0 (
        set "PYTHON_CMD=py"
        echo Using py launcher
    )
)

REM Check if frontend is built
if not exist "%~dp0frontend\dist" (
    echo Building frontend...
    cd /d "%~dp0frontend"
    call npm install
    call npm run build
    if !errorlevel! neq 0 (
        echo ERROR: Frontend build failed!
        pause
        exit /b 1
    )
)

REM Create logs directory
mkdir "%~dp0logs" 2>nul

echo.
echo [1/2] Starting Backend (Production Mode)...
cd /d "%~dp0backend"
start "DSQ Backend 24/7" cmd /c "title DSQ Backend 24/7 && echo Starting Backend... && %PYTHON_CMD% -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --log-level info > ..\logs\backend.log 2>&1"

REM Wait for backend to start
echo Waiting for backend to initialize...
timeout /t 10 /nobreak >nul

echo [2/2] Starting Frontend (Production Mode)...
cd /d "%~dp0"
start "DSQ Frontend 24/7" cmd /c "title DSQ Frontend 24/7 && echo Starting Frontend SPA Server... && %PYTHON_CMD% spa_server.py 5173 frontend\dist > logs\frontend.log 2>&1"

REM Wait for frontend to start
timeout /t 5 /nobreak >nul

echo.
echo ========================================
echo Testing Services...
echo ========================================

REM Test backend
curl -s http://localhost:8000/docs >nul 2>&1
if %errorlevel% equ 0 (
    echo ✓ Backend API is responding (http://localhost:8000)
) else (
    echo ⚠️  Backend API not responding yet...
    echo   Check backend.log if issues persist
)

REM Test frontend
curl -s http://localhost:5173 >nul 2>&1
if %errorlevel% equ 0 (
    echo ✓ Frontend is responding (http://localhost:5173)
) else (
    echo ⚠️  Frontend not responding yet...
    echo   Check frontend.log if issues persist
)

echo.
echo ========================================
echo DSQ System Started Successfully!
echo ========================================
echo.
echo 🌐 URLs:
echo   Backend API: http://localhost:8000
echo   Frontend:    http://localhost:5173
echo   API Docs:    http://localhost:8000/docs
echo.
echo 📊 Monitoring:
echo   Backend Window: "DSQ Backend 24/7"
echo   Frontend Window: "DSQ Frontend 24/7"
echo   Logs: %~dp0logs\
echo.
echo 🛑 To Stop:
echo   Close both "DSQ Backend 24/7" and "DSQ Frontend 24/7" windows
echo   Or run: stop_24_7.bat
echo.
echo ✅ This setup runs 24/7 without Windows Services
echo    Both processes will restart if windows are accidentally closed
echo.
echo 🌍 Muốn chạy system thì truy cập vào link: http://%MACHINE_IP%:5173/
echo.
echo Press any key to close this setup window...
pause >nul
